version: "2"

services:
  concert-diary-fe:
    build:
      context: .
      dockerfile: Dockerfile
    container_name: "concert-diary-fe"
    restart: unless-stopped
    ports:
      - "${PORT}:80"
